### ISSUE TITLE
Question: How to run example with `cliquebait`

### ISSUE THREAD

**Issue by sectore** [f-o-a-m/purescript-web3-example#7]
Following [Purescript-web3 presentation](https://youtu.be/Yc82LlT6vC0?t=57m36s) (from 57:30 min) I did following steps:

1. Running [`cliquebait`](https://github.com/f-o-a-m/cliquebait)
```
sudo docker run --rm -it -p 8545:8545 foamspace/cliquebait:latest
``` 

2. Run migration of `SimpleStorage` by using [`purescript-web3-tests`](https://github.com/f-o-a-m/purescript-web3-tests)
```
yarn truffle --network=localhost         
yarn run v1.5.1
$ ./node_modules/.bin/truffle deploy --network=localhost
Using network 'localhost'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0xd3ca9d9200a98bc035b6e8116df6df133aeb079b5d6956c10b02b2a19d0fcb95
  Migrations: 0xf07814328be53b09fe699670b78680c0b6e2d675
Saving successful migration to network...
  ... 0x03e759f8a7ba11b97cbf8051839eb1d5cdca2020c47944725c13e0648719e8f6
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Replacing SimpleStorage...
  ... 0xff2681dc10d78fdc7507b843713df8361ddb5739a4f0066d83daf7fd99c09f2b
  SimpleStorage: 0xe5bb2d4825baafe52250b90b8029a0eb38305892
  Replacing ComplexStorage...
  ... 0x9a5a342147868dbb27c80ec4a3a357b7d45c8ca95d82cba62b119683888ebda1
  ComplexStorage: 0x9f9f2d8880f410b084b2e41106ad26e7ba0fb57c
  Replacing MockERC20...
  ... 0x829b5aeb72fece2d01781b06f207c2c1c7fab78a4ddbc5818b7e32168992462c
  MockERC20: 0x84d9f0474dcfaef53507f9ac25f6ed275173b3c3
  Replacing SimpleErrorTest...
  ... 0x3b06a3224ab8fef0599bfc377e0427e4e5b7b6f00d497afc2b74191c7c994ff3
  SimpleErrorTest: 0x8bef61d985b18b223aff85ab0857bea8e306e48d
  Replacing PayableTest...
  ... 0xb38103e30c85b528caf8faccafa548d647a8bf6ea03ae1f0899fdf0aae42fc09
  PayableTest: 0x98d5f1dee2022184ce88188054461faa07f5c099
Saving successful migration to network...
  ... 0xc6f243293e01f41e6f9e8e05d937594e42af0ceab8a354f94482f7ca16066475
Saving artifacts...
Done in 50.93s.
```

3. Running tests of `purescript-web3-tests` showed me that every runs well with `cliquebait`. 
```
NODE_URL=http://localhost:8545/ yarn test
...
Summary
9/9 tests passed

* Tests OK.
Done in 125.06s.
```

4. However, using `SimpleStorage` address `0xe5bb2d4825baafe52250b90b8029a0eb38305892` copied from step 2 failed. The form of the web app shows me an error about `Current Count: error occurred while fetching count, retrying ...`

The `SimpleStorage` address was added to `SIMPLE_STORAGE_ADDRESS` to run `purescript-web3-example` with `webpack` as follow:

```
SIMPLE_STORAGE_ADDRESS=0xe5bb2d4825baafe52250b90b8029a0eb38305892 yarn webpack-dev-server
```  

_Screen shot_

![screenshot from 2018-03-26 18-48-42](https://user-images.githubusercontent.com/47693/37920237-9a9433de-3126-11e8-8258-4ae7c4d1fb1a.png)

Also, submitting the form to increase `count` failed by using a non-zero ETH balance address, which has been created with Metamask (Rinkeby testnet): `Failed to create transaction, try again`.

_Screen shot_

![screenshot from 2018-03-26 18-49-11](https://user-images.githubusercontent.com/47693/37920282-bedcb270-3126-11e8-810e-c33d664b09dd.png)

Do I miss something?

**Comment by iostat** [comment]
If you're running against Cliquebait, you'll have to tell Metamask to use the "Localhost 8545" provider so that it uses your local Cliquebait blockchain. Additionally, you'll have to give your Metamask address some cliquebait ether by running:

```
docker exec -it CLIQUEBAIT_CONTAINER_ID geth attach http://localhost:8545/ --exec 'eth.sendTransaction({from: eth.coinbase, to: "YOUR_METAMASK_ACCOUNT_ADDRESS"})'
```
you can find the CLIQUEBAIT_CONTAINER_ID by running `docker ps`. Note that if you have `geth` installed locally you can drop the `docker exec -it CLIQUEBAIT_CONTAINER_ID` part.

**Comment by sectore** [comment]
Container / `Cliquebait` is running 
```
sudo docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                          NAMES
c2335397025b        foamspace/cliquebait:latest   "/cliquebait/run.bash"   58 seconds ago      Up 57 seconds       0.0.0.0:8545->8545/tcp, 30303/tcp, 30303/udp   silly_lumiere
```
but MetaMask seems to have some issues to access `Localhost 8545` - it can't connect to it:

![metamask2](https://user-images.githubusercontent.com/47693/37927695-1421d314-313b-11e8-972a-eeeaa986318d.png)

![metamask1](https://user-images.githubusercontent.com/47693/37927684-0fa700de-313b-11e8-84d9-a95797e6f437.png)


BTW: The part of giving some Cliquebait to Rinkeby address runs well
```
 geth attach http://localhost:8545/ --exec 'eth.sendTransaction({from: eth.coinbase, to: "0xF13463f80eFdCCe9bfd213171D30fCA8f59137Fc"})'
"0xf88a1bb59ecc1415260eed7501e4ffdf89a6c6bfb31c0485683879dc4e326be4"
```

**Comment by sectore** [comment]
The issue to connect private network `Localhost 8545` could be fixed by using `MetaMask` on Chrome (not on Firefox). However, is your example complete to send some ETH to Rinkeby address? It seems there are any other params are missing https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction

**Comment by sectore** [comment]
@iostat Any idea about the issue I've had to send ether to metamask address (see previous comment ^)?

**Comment by iostat** [comment]
Geth fills in the missing values with sensible defaults. You can run `eth.getTransaction(“0xTHE_HASH_THAT_GETS_PRINTED”)` to see for yourself. Assuming you’re not running a second geth node locally which would silently conflict with the one you’re running in Docker, the example I provided should just work.

**Comment by iostat** [comment]
Also, keep in mind that cliquebait chains are ephemeral (by design). If you stop the container you will lose that chain and have to re-fund yourself and redeploy any contracts.

**Comment by sectore** [comment]
Ah, I have to add a value, because default value of a Tx's is `0` ETH only:
```
geth attach http://localhost:8545/ --exec 'eth.sendTransaction({from: eth.coinbase, to: "0xF13463f80eFdCCe9bfd213171D30fCA8f59137Fc"})'
"0xd8c71422357b4964e9a386fc7c3e2996206de4dac4d4561dd4e8258efb9dd9bd"
```
```
geth attach http://localhost:8545/ --exec 'eth.getTransaction("0xd8c71422357b4964e9a386fc7c3e2996206de4dac4d4561dd4e8258efb9dd9bd")'                      
{
  blockHash: "0xed34457f44932439343f5154afb1d5633143edf2d99e1fbb55f0a415accc4a6f",
  blockNumber: 53,
  from: "0x2733f86b2585049d1174630a8c3a58ea3ed9111f",
  gas: 90000,
  gasPrice: 100000000000,
  hash: "0xd8c71422357b4964e9a386fc7c3e2996206de4dac4d4561dd4e8258efb9dd9bd",
  input: "0x",
  nonce: 8,
  r: "0xd8e72998208aef9c74672f149accadffc51aaf1298a3053bf8eacca1e801c0fb",
  s: "0x60a7932d983e7eed3f1fe5ea4bb887211f6eae79666d31a6576c9c861ac33181",
  to: "0xf13463f80efdcce9bfd213171d30fca8f59137fc",
  transactionIndex: 0,
  v: "0xcd25a",
  value: 0
}
```

And the value has to be higher than `gas * gasPrice` of course. So that following works:
```
geth attach http://localhost:8545/ --exec 'eth.sendTransaction({from: eth.coinbase, to: "0xF13463f80eFdCCe9bfd213171D30fCA8f59137Fc", value: web3.toWei(0.05, "ether")})'
````

```
geth attach http://localhost:8545/ --exec 'eth.getTransaction("0xf9a2246fe8694411605c75c12a0884117a323b0435fd8acf515b68acc4b90687")'
{
  blockHash: "0xd93b6bb8576f8bcef9f3eb42cd702ac436835ded538d32866d9053b06b1ca6f2",
  blockNumber: 170,
  from: "0x2733f86b2585049d1174630a8c3a58ea3ed9111f",
  gas: 90000,
  gasPrice: 100000000000,
  hash: "0xf9a2246fe8694411605c75c12a0884117a323b0435fd8acf515b68acc4b90687",
  input: "0x",
  nonce: 10,
  r: "0x933cd80abc8c09fef7b60f16c57b9a9d41bef484f8ba9fb59219349b5d0d762f",
  s: "0x42055f8e2b10f0540a8c617b2c78f64e8a2809632b7ba92fa1830b7db472006b",
  to: "0xf13463f80efdcce9bfd213171d30fca8f59137fc",
  transactionIndex: 0,
  v: "0xcd25a",
  value: 50000000000000000
}
```
So finally MetaMask's address has received some ETH from `cliquebait`

![metamask_address_received_value](https://user-images.githubusercontent.com/47693/38018662-d0da6a80-3275-11e8-81b0-deac3895624b.png)

Now I can submit values from `purescript-web3-example` form to confirm this Tx by MetaMask
 
![metamask_address_confirm_tx](https://user-images.githubusercontent.com/47693/38020254-04d3f7da-327a-11e8-8d89-c8e2ebeb2045.png)

And all Tx have been received in MetaMask's address. 

Anyway, the `count` is still not set or not available `Current Count: error occurred while fetching count, retrying ...` 

![screenshot from 2018-03-28 11-22-17](https://user-images.githubusercontent.com/47693/38020428-7aec3cca-327a-11e8-8d1a-449d965a653f.png)

@iostat Do I have to send some data with the first transaction from  `cliquebait` to MetaMask address? It seems that in a Tx of the presentation (1:01:51 - [link here](https://www.youtube.com/watch?v=Yc82LlT6vC0&feature=youtu.be&t=57m36s) are the function `setCount` as data defined 
```Function: setCount(uint256 _count) *** 
...``` Or do I miss something else?

**Comment by iostat** [comment]
Ah, I could've sworn I put a `value` in that example. Good catch!
Note that `value` doesn't have to be higher that `gasLimit * gasPrice`, the gas costs get deducted from your account after the transaction, not from the transaction value. 

As far as your issue, I'm at a loss here, I've pinged the devs of the example to see if they have any wisdom to offer.

**Comment by blinky3713** [comment]
First things first, you should note that the tests has a different simple storage than the example app -- the tests repo wasn't really made to support the example app, but I guess we should change it for consistency. This does not explain your problem, but you should be aware.

(ps-web3-example SimpleStorage)[https://github.com/f-o-a-m/purescript-web3-example/blob/master/contracts/src/SimpleStorage.sol]

(ps-web3-tests SimpleStorage)[https://github.com/f-o-a-m/purescript-web3-tests/blob/master/contracts/SimpleStorage.sol]

The example app is not meant to be run with cliquebait because it expects that the user can use uPort if they want to, which is not baked into the cliquebait image. One could suggest that we check the networkId before continuing with the example app, but probably the best solution here is to make a warning in the README that you must be using Rinkeby because of the uPort dependency. 

Note: uPort has migrated all recent work to Rinkeby, even though they used to support more test networks.

**Comment by blinky3713** [comment]
added this to the [README](https://github.com/f-o-a-m/purescript-web3-example/commit/0dcac80bfa8023514633bd8ec4a3373b2a0b2f54)

**Comment by blinky3713** [comment]
Also note, the uPort dependency got added about a month ago, but before that it would have been possible to run on cliquebait. The video is just outdated in that sense. Sorry about that.

**Comment by sectore** [comment]
@iostat @blinky3713 Thanks guys! Finally I got `purescript-web3-example` running.  The last missing part was deploying a [`SimpleStorage`](https://github.com/f-o-a-m/purescript-web3-example/blob/master/contracts/src/SimpleStorage.sol) contract to `Rinkeby`. 

For deploying that contract ^ I did following steps:
1. Run `rinkeby` locally using [`geth`](https://geth.ethereum.org/):
```
geth --rinkeby --rpc console --rpcapi db,eth,net,web3,personal
```

2. Use [`mist`](https://github.com/ethereum/mist) to create a contract while connecting to `Rinkeby` .

Please let me know if there is a simpler way (e.g. using `truffle` or so) to create a `SimpleStorage` contract. It would be nice to have that info at the `README`, too ;)

**Comment by sectore** [comment]
Nice, thanks!

_Closing the issue right now..._
